### ISSUE TITLE
rake update_resources aborted - windows 10 x64

### ISSUE THREAD

**Issue by gjko** [NREL/OpenStudio-BEopt#130]
Rake file fails to locate OpenStudio.

```
OpenStudio did not load, but most functionality is still available. Will continue...
rake aborted!
LoadError: cannot load such file -- openstudio
C:/Users/X/Documents/x/Energy Model work folder/Residential OpenStudio Measures/OpenStudio-BEopt-master/Rakefile:272:in `require'
C:/Users/X/Documents/x/Energy Model work folder/Residential OpenStudio Measures/OpenStudio-BEopt-master/Rakefile:272:in `block in <top (required)>'
Tasks: TOP => update_resources
```

In a previous attempt, failed to load a module of OpenStudio with the following error: 
```

rake update_resources
OpenStudio did not load, but most functionality is still available. Will continue...
rake aborted!
LoadError: 1114: A dynamic link library (DLL) initialization routine failed.   - C:/Program Files/OpenStudio 1.14.0/Ruby/openstudio/openstudioutilitiescore.so
C:/Program Files/OpenStudio 1.14.0/Ruby/openstudio.rb:107:in `require'
C:/Program Files/OpenStudio 1.14.0/Ruby/openstudio.rb:107:in `<top (required)>'
```

**Comment by gjko** [comment]
I had this error with Ruby 2.3.3 (x64).
With Ruby 2.0.0-p648 (x64) it worked.

**Comment by shorowit** [comment]
Yes, see here: https://github.com/NREL/OpenStudio/wiki/OpenStudio-Version-Compatibility-Matrix

Note that OpenStudio 2.0.1 and higher will require ruby 2.2.4.
