### ISSUE TITLE
Error: Set Residential Eaves 

### ISSUE THREAD

**Issue by gjko** [NREL/OpenStudio-BEopt#133]
The measure "Set Residential Eaves " gives the following error:

![err_geometry_eaves](https://cloud.githubusercontent.com/assets/14098958/23801454/d50509ae-0575-11e7-8184-702c12921ce1.JPG)

```
C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript/user_script.rb:910:in `initialize': invalid null reference Expected argument 0 of type std::vector< openstudio::Point3d,std::allocator< openstudio::Point3d > > const &, but got NilClass nil (ArgumentError)

	in SWIG method 'Surface'

	from C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript/user_script.rb:910:in `new'

	from C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript/user_script.rb:910:in `block in run'

	from C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript/user_script.rb:718:in `each'

	from C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript/user_script.rb:718:in `run'

	from in.rb:364:in `<main>'


Script executing from: C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript
Found argument 'roof_structure' with value 'truss, cantilever'.
Found argument 'eaves_depth' with value '1'.
Found UserScript 'Set Residential Eaves'.
```

I've set a flat roof, I don't know if this influence the measure.

**Comment by shorowit** [comment]
Can you attach your .osm?

**Comment by gjko** [comment]
https://www.dropbox.com/s/9nql78wk6w8i97j/AF_SeedModel_v2_2.Geometry.osm?dl=0

**Comment by joseph-robertson** [comment]
This error may no longer be relevant. See #165.
